- hosts: localhost
  vars:
        region: ap-south-1
        security_group: msecure
  vars_files:
    - aws_keys.yml
    
  tasks:
    - name: Creating a security group
      ec2_group:
        name: "{{ security_group }}"
        description: The webservers security group
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Launching Instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        instance_type: t2.micro
        image: ami-5b673c34
        group: "{{ security_group }}"
      register: ec2

#    - name: Wait for SSH to come up
#      wait_for:
#           host: "{{ item.public_ip }}"
#           port: 22 
#           state: started 
#      with_items: "{{ ec2.instances }}"



